[package]
name        = "rustspray"
version     = "0.1.0"
edition     = "2021"
license     = "MIT"
description = "A Rust-based camera-and-sprayer system for precision weed control in agriculture"
homepage    = "https://github.com/cropcrusaders/Rust-Spray"
repository  = "https://github.com/cropcrusaders/Rust-Spray"
readme      = "README.md"
keywords    = ["agriculture", "precision-farming", "weed-control", "rust", "opencv"]
categories  = ["hardware", "embedded", "science", "image-processing"]

# ─────────────────────────────────────────────────────────────────────────────
[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "open_weed_locator"
path = "examples/open_weed_locator.rs"

# ─────────────────────────────────────────────────────────────────────────────
[dependencies]

# OpenCV bindings (disable defaults, enable only needed modules)
opencv = { version = "0.94.4", default-features = false, features = [
  "clang-runtime",
  "highgui",
  "imgproc",
  "imgcodecs",
  "videoio",
  "objdetect"
], optional = true }

# Configuration loading
serde = { version = "1.0", features = ["derive"] }
toml  = "0.8"

# CLI, logging, error handling
clap       = { version = "4.5", features = ["derive"] }
log        = "0.4"
env_logger = "0.11"
thiserror  = "1.0"

# Date/time and data export for weed locator functionality
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Raspberry Pi GPIO support (enabled only on ARM platforms)
[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
rppal = { version = "0.15", optional = true }

# Raspberry Pi camera (V4L2)
rscam = { version = "0.5", optional = true }

# ─────────────────────────────────────────────────────────────────────────────
[features]

# Default features for ARM targets (Raspberry Pi)
default = ["opencv"]

# Feature for host builds
host = ["opencv"]

# ARM-specific features (for cross-compilation)
with-rppal = ["rppal"]
picam      = ["rscam"]

# ARM feature combinations for different scenarios
arm-gpio = ["with-rppal", "picam"]                    # ARM GPIO without OpenCV
arm-core = ["with-rppal"]                             # Basic ARM support
arm-camera = ["picam"]                                # Camera support only

# Convenience feature for full Raspberry Pi support
raspberry-pi = ["with-rppal", "picam"]

# ─────────────────────────────────────────────────────────────────────────────
[package.metadata.deb]
maintainer = "Crop Crusaders <dev@cropcrusaders.com>"
license-file = ["LICENSE"]
depends = "libc6"
assets = [
  ["target/aarch64-unknown-linux-gnu/release/rustspray", "usr/bin/", "755"],
  ["config/Config.toml", "etc/rustspray/config.toml", "644"],
]

