[package]
name        = "rustspray"
version     = "0.1.0"
edition     = "2021"
license     = "MIT"
description = "A Rust-based camera-and-sprayer system for precision weed control in agriculture"
homepage    = "https://github.com/cropcrusaders/Rust-Spray"
repository  = "https://github.com/cropcrusaders/Rust-Spray"
readme      = "README.md"
keywords    = ["agriculture", "precision-farming", "weed-control", "rust", "opencv"]
categories  = ["hardware", "embedded", "science", "image-processing"]

# ─────────────────────────────────────────────────────────────────────────────
[dependencies]

# OpenCV bindings (disable defaults, enable only needed modules)
opencv = { version = "0.89", default-features = false, features = [
  "clang-runtime",
  "highgui",
  "imgproc",
  "imgcodecs",
  "videoio",
  "objdetect"
] }

# Configuration loading
serde = { version = "1.0", features = ["derive"] }
toml  = "0.8"

# CLI, logging, error handling
clap       = { version = "4.5", features = ["derive"] }
log        = "0.4"
env_logger = "0.11"
thiserror  = "1.0"

# Raspberry Pi GPIO support (enabled only on ARM platforms)
rppal = { version = "0.15", optional = true }

# Raspberry Pi camera (V4L2)
rscam = { version = "0.5", optional = true }

# ─────────────────────────────────────────────────────────────────────────────
[features]

# GPIO enabled by default (for ARM targets like Raspberry Pi)
default    = ["with-rppal"]
with-rppal = ["rppal"]
picam      = ["rscam"]

# ─────────────────────────────────────────────────────────────────────────────
# Platform guard: only include `rppal` on ARM and AARCH64 targets
[target.'cfg(not(any(target_arch = "arm", target_arch = "aarch64")))'.dependencies]
rppal = { version = "0.15", optional = true }

[package.metadata.deb]
maintainer = "Crop Crusaders <dev@cropcrusaders.com>"
license-file = ["LICENSE"]
depends = "libc6"
assets = [
  ["target/aarch64-unknown-linux-gnu/release/rustspray", "usr/bin/", "755"],
  ["config/Config.toml", "etc/rustspray/config.toml", "644"],
]

