[package]
name        = "rustspray"
version     = "0.1.0"
edition     = "2021"
license     = "MIT"
description = "A Rust-based camera-and-sprayer system for precision weed control in agriculture"
homepage    = "https://github.com/cropcrusaders/Rust-Spray"
repository  = "https://github.com/cropcrusaders/Rust-Spray"
readme      = "README.md"
keywords    = ["agriculture", "precision-farming", "weed-control", "rust"]
categories  = ["hardware", "embedded", "science", "image-processing"]

[[example]]
name = "four_lane"
path = "examples/four_lane.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
crossbeam-channel = "0.5"

[target.'cfg(target_arch = "arm")'.dependencies]
rppal = "0.15"

[package.metadata.deb]
maintainer = "Crop Crusaders <dev@cropcrusaders.com>"
license-file = ["LICENSE"]
depends = "libc6"
assets = [
  ["target/aarch64-unknown-linux-gnu/release/rustspray", "usr/bin/", "755"],
  ["config/Config.toml", "etc/rustspray/config.toml", "644"],
]
