
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cropcrusaders/aarch64-opencv:latest"
dockerfile = "docker/aarch64-opencv.dockerfile"
xargo = false


[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cropcrusaders/armv7-opencv:latest"
