# Cross.toml ─ Variables cross should pass into the build container
[target.aarch64-unknown-linux-gnu.env]
OPENCV_DOWNLOAD       = "1"   # fetch & build OpenCV from source
OPENCV_DISABLE_PROBES = "1"   # skip pkg-config / cmake probing
