# Cross.toml
[build]
default-target = "aarch64-unknown-linux-gnu"

# Install OpenCV & tooling inside the ARM64 build container
pre-build = [
  "apt-get update -qq",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y \\",
  "  libopencv-dev pkg-config clang libclang-dev"
]

# Pass through PKG_CONFIG_ALLOW_CROSS so pkg-config will probe cross-arch libs
[build.env]
passthrough = ["PKG_CONFIG_ALLOW_CROSS=1"]

# For the aarch64 target, override the pkg-config search path
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  # point at the ARM64 pkgconfig directory
  "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig",
  "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig"
]
