# Cross.toml
[build]
default-target = "aarch64-unknown-linux-gnu"

pre-build = [
  # 1) enable arm64 multi-arch
  "dpkg --add-architecture arm64",
  "apt-get update -qq",
  # 2) install just the ARM64 OpenCV dev packages & pkg-config
  "DEBIAN_FRONTEND=noninteractive apt-get install -y \\",
  "  libopencv-dev:arm64 libopencv-contrib-dev:arm64 pkg-config:arm64",
  # 3) create the pkgconfig dir and symlink opencv4.pc
  "mkdir -p /usr/lib/aarch64-linux-gnu/pkgconfig",
  "ln -sf /usr/lib/aarch64-linux-gnu/pkgconfig/opencv.pc \\",
  "      /usr/lib/aarch64-linux-gnu/pkgconfig/opencv4.pc"
]

[build.env]
passthrough = ["PKG_CONFIG_ALLOW_CROSS=1"]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig",
  "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig",
  "CXX=aarch64-linux-gnu-g++"
]
