# Cross.toml
[build]
default-target = "aarch64-unknown-linux-gnu"

# Pre-build steps inside the AArch64 container:
pre-build = [
  # enable the “universe” archive so contrib packages exist
  "apt-get update -qq",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common",
  "add-apt-repository universe",
  "DEBIAN_FRONTEND=noninteractive apt-get update -qq",
  # install both the core and the contrib dev packages (all built as ARM64 here)
  "DEBIAN_FRONTEND=noninteractive apt-get install -y \\",
  "  libopencv-dev libopencv-contrib-dev pkg-config"
]

[build.env]
# allow pkg-config to probe for cross-arch libs
passthrough = ["PKG_CONFIG_ALLOW_CROSS=1"]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  # point pkg-config at the ARM64 pkgconfig dir
  "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig",
  "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig",
  # ensure the right cross-linker
  "CXX=aarch64-linux-gnu-g++"
]
