# Cross.toml
[build]
default-target = "aarch64-unknown-linux-gnu"

# Pre-build steps *inside* the ARM64 container:
pre-build = [
  "apt-get update -qq",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y \\",
  "  libopencv-dev libopencv-contrib-dev pkg-config build-essential",
]

[build.env]
# let pkg-config probe cross-arch libs, and point opencv-rust at "opencv.pc"
passthrough = [
  "PKG_CONFIG_ALLOW_CROSS=1",
  "OPENCV_PKGCONFIG_NAME=opencv",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  # only look in the ARM64 pkgconfig dir
  "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig",
  "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig",
  # use the right cross-linker
  "CXX=aarch64-linux-gnu-g++",
  "OPENCV_PKGCONFIG_NAME=opencv",
]
