# Cross.toml  ─ put at project root
[target.aarch64-unknown-linux-gnu]
env = {                       # <- table called `env`
  OPENCV_DOWNLOAD       = "1",   # download & build OpenCV
  OPENCV_DISABLE_PROBES = "1"    # skip pkg-config / cmake probing
}
