# Cross.toml
[build]
default-target = "aarch64-unknown-linux-gnu"

# In the aarch64 container, install OpenCV + tooling
pre-build = [
  "apt-get update -qq",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y \\",
  "  libopencv-dev pkg-config clang libclang-dev"
]
