
# Cross-compilation configuration for Rust-Spray
# Using standard cross-rs images for better compatibility

[target.aarch64-unknown-linux-gnu]
# Use standard cross-rs image without OpenCV (we'll handle OpenCV via pkg-config if needed)
xargo = false

[target.armv7-unknown-linux-gnueabihf]
# Use standard cross-rs image without OpenCV (we'll handle OpenCV via pkg-config if needed)
xargo = false
