FROM ubuntu:22.04

# Enable the ARMHF architecture and clean up unused ones
RUN dpkg --add-architecture armhf \
    && dpkg --remove-architecture i386 || true \
    && apt-get -o Acquire::Retries=3 update \
    && apt-get -o Acquire::Retries=3 install -y --no-install-recommends \
        libopencv-dev:armhf \
        pkg-config:armhf \
        ninja-build:armhf \
    && rm -rf /var/lib/apt/lists/*
