FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libopencv-dev \
        pkg-config \
        ninja-build && \
    rm -rf /var/lib/apt/lists/*
