FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main
RUN find /etc/apt -name '*.list' -print0 \
        | xargs -0 sed -i \
            -e 's|archive.ubuntu.com|ports.ubuntu.com|g' \
            -e 's|security.ubuntu.com|ports.ubuntu.com|g' && \
    apt-get -o Acquire::Retries=3 update && \
    apt-get -o Acquire::Retries=3 --fix-missing install -y --no-install-recommends \
        libopencv-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*
