FROM ubuntu:22.04

# Enable the ARM64 architecture and remove unnecessary ones
RUN dpkg --add-architecture arm64 \
    && dpkg --remove-architecture i386 || true \
    && apt-get -o Acquire::Retries=3 update \
    && apt-get -o Acquire::Retries=3 install -y --no-install-recommends \
        libopencv-dev:arm64 \
        pkg-config:arm64 \
        ninja-build:arm64 \
    && rm -rf /var/lib/apt/lists/*
