[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=generic"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=generic"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = []
