[target.aarch64-unknown-linux-gnu]
runner = "cross"
linker = "aarch64-linux-gnu-gcc"

#[build]
# Uncomment to cross compile for Raspberry Pi
# target = "aarch64-unknown-linux-gnu"

[unstable]
build-std = ["std"]
