[target.aarch64-unknown-linux-gnu]
linker = "zig"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native", "-C", "lto=thin"]

[target.aarch64-unknown-linux-musl]
linker = "zig"
rustflags = ["-C", "link-arg=-static", "-C", "target-cpu=native", "-C", "lto=thin"]

[target.armv7-unknown-linux-gnueabihf]
linker = "zig"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-feature=+neon", "-C", "lto=thin"]
