# RustSpray Example Configuration File
# Copy this file to config/config.toml and adjust the values for your setup.

# Camera settings
[camera]
# Camera device path
# Check your system (e.g., use 'ls /dev/video*' to find available cameras)
device = "/dev/video2"
# Image resolution
# Higher resolutions (e.g., 1280x720) improve detection but may slow performance
resolution_width = 1280
resolution_height = 720
# Use the Raspberry Pi camera driver (true/false)
use_rpi_cam = false

# Detection settings
[detection]
# Weed detection algorithm
# "exg" is fast and simple; try "hsv" for more complex color-based detection
algorithm = "hsv"
# ExG parameters (used if algorithm is "exg" or "exhsv")
exg_min = 20    # Lowered for more sensitivity to green
exg_max = 200   # Adjusted based on lighting conditions
# HSV parameters (used if algorithm is "hsv" or "exhsv")
hue_min = 25          # Slightly wider hue range for weeds
hue_max = 100
brightness_min = 10   # Increased to reduce noise in low light
brightness_max = 220
saturation_min = 40   # Higher saturation for vivid greens
saturation_max = 250
# Minimum weed area in pixels
# Increase if small detections are unwanted; depends on resolution
min_area = 15.0
# Invert hue if weeds appear in unexpected color ranges
invert_hue = true

# Spraying settings
[spray]
# GPIO pins for sprayers
# Example uses pins 23, 24, 25, 26; update to match your Raspberry Pi wiring
pins = [23, 24, 25, 26]
# Sprayer activation time in milliseconds
# Longer duration (e.g., 200ms) ensures sufficient spray
activation_duration_ms = 200
# Enable spraying (set to false for open weed locator mode)
enabled = true

# GPS settings for location tracking
[gps]
# Enable GPS tracking (set to true if GPS hardware available)
enabled = false
# Mock GPS coordinates (used when GPS hardware not available or for testing)
# These coordinates represent a field location (latitude, longitude)
mock_latitude = 42.0314  # Example: Iowa, USA
mock_longitude = -93.5854

# Data logging settings for weed detection events
[logging]
# Enable logging of detection events
enabled = true
# Output file prefix (extensions .json/.csv added automatically)
output_file = "weed_detections"
# Output format: "json", "csv", or "both"
format = "json"
# Auto-flush after each detection (recommended for real-time use)
auto_flush = true
