# RustSpray Example Configuration File
# Copy this file to config/config.toml and adjust the values for your setup.

# Camera settings
[camera]
# Camera device path
# Check your system (e.g., use 'ls /dev/video*' to find available cameras)
device = "/dev/video2"
# Image resolution
# Higher resolutions (e.g., 1280x720) improve detection but may slow performance
resolution_width = 1280
resolution_height = 720

# Detection settings
[detection]
# Weed detection algorithm
# "exg" is fast and simple; try "hsv" for more complex color-based detection
algorithm = "hsv"
# ExG parameters (used if algorithm is "exg" or "exhsv")
exg_min = 20    # Lowered for more sensitivity to green
exg_max = 200   # Adjusted based on lighting conditions
# HSV parameters (used if algorithm is "hsv" or "exhsv")
hue_min = 25          # Slightly wider hue range for weeds
hue_max = 100
brightness_min = 10   # Increased to reduce noise in low light
brightness_max = 220
saturation_min = 40   # Higher saturation for vivid greens
saturation_max = 250
# Minimum weed area in pixels
# Increase if small detections are unwanted; depends on resolution
min_area = 15.0
# Invert hue if weeds appear in unexpected color ranges
invert_hue = true

# Spraying settings
[spray]
# GPIO pins for sprayers
# Example uses pins 23, 24, 25, 26; update to match your Raspberry Pi wiring
pins = [23, 24, 25, 26]
# Sprayer activation time in milliseconds
# Longer duration (e.g., 200ms) ensures sufficient spray
activation_duration_ms = 200
