name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, aarch64-unknown-linux-musl]
    env:
      USE_TOOLCHAIN: ${{ env.USE_TOOLCHAIN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Run dev checks
        run: cargo xtask dev
      - name: Build
        run: |
          if [ "$USE_TOOLCHAIN" = "true" ]; then
            ./scripts/toolchain-build.sh
          else
            ./scripts/cross-build.sh
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustspray-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/
