name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    needs: [build-aarch64-image, build-armv7]
    runs-on: ubuntu-latest
    env:
      GHCR_USER: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            image: ghcr.io/${{ github.repository_owner }}/aarch64-opencv:latest
            arch: arm64
          - target: armv7-unknown-linux-gnueabihf
            image: ghcr.io/${{ github.repository_owner }}/armv7-opencv:latest
            arch: armv7
            continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross CLI from Git
        # The cross crate is no longer published on crates.io.
        # Install straight from the repository and lock dependencies.
        run: cargo install --git https://github.com/cross-rs/cross cross --locked

      - name: Add cargo bin to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USER }}
          password: ${{ env.GHCR_TOKEN }}

      - name: Install cargo-deb
        if: github.event_name == 'release'
        run: cargo install cargo-deb --locked

      - name: Pull cross image
        run: docker pull ${{ matrix.image }}

      - name: +8 GB swap to survive clang
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8

      - name: Build
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
          CARGO_INCREMENTAL: "0"                 # still saves memory
        run: cross build --release --target ${{ matrix.target }} --verbose

      - name: Upload artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: rustspray-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/rustspray

      - name: Build Debian package
        if: github.event_name == 'release'
        run: cargo deb --no-build --target ${{ matrix.target }}

      - name: Upload Debian package
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/${{ matrix.target }}/debian/rustspray_*.deb
          asset_name: rustspray_${{ github.event.release.tag_name }}_${{ matrix.arch }}.deb
          asset_content_type: application/vnd.debian.binary-package

  build-aarch64-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "latest"
      DOCKERFILE_PATH: "docker/Dockerfile.aarch64"
      GHCR_USER: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        if: env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USER }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Build and push ARM64 builder image
        if: env.GHCR_TOKEN != ''
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ env.GHCR_USER }}/aarch64-opencv:${{ env.IMAGE_TAG }} \
            -f ${{ env.DOCKERFILE_PATH }} \
            --push .
      - name: Build ARM64 image without push
        if: env.GHCR_TOKEN == ''
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ env.GHCR_USER }}/aarch64-opencv:${{ env.IMAGE_TAG }} \
            -f ${{ env.DOCKERFILE_PATH }} \
            --load .

  build-armv7:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "latest"
      DOCKERFILE_PATH: "docker/Dockerfile.armv7"
      GHCR_USER: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU (needed for multi-arch builds)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        if: env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USER }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Build ARMv7 builder image
        run: |
          docker build \
            -t ghcr.io/${{ env.GHCR_USER }}/armv7-opencv:${{ env.IMAGE_TAG }} \
            -f ${{ env.DOCKERFILE_PATH }} .
      - name: Push image
        if: env.GHCR_TOKEN != ''
        run: docker push ghcr.io/${{ env.GHCR_USER }}/armv7-opencv:${{ env.IMAGE_TAG }}
