name: Cross-Compile for AArch64

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-aarch64:
    name: Build for aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build with cross for aarch64
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Upload aarch64 binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-aarch64-binary
          path: target/aarch64-unknown-linux-gnu/release/*
