name: Yocto Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-yocto:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Ensure Poky sources
        run: |
          if [ ! -e yocto/poky/oe-init-build-env ]; then
            git clone --depth 1 https://git.yoctoproject.org/git/poky yocto/poky
          fi

      - name: Ensure meta-openembedded layer
        run: |
          if [ ! -e yocto/meta-openembedded/meta-oe ]; then
            git clone --depth 1 https://github.com/openembedded/meta-openembedded.git yocto/meta-openembedded
          fi

      - name: Set up Poky build environment
        run: |
          source yocto/poky/oe-init-build-env yocto/build
          bitbake rust-spray-image

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-spray-image
          path: yocto/build/tmp/deploy/images
