name: Yocto Build

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:  # Manual trigger only
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM

jobs:
  build-yocto:
    runs-on: ${{ github.repository_owner == 'cropcrusaders' && 'self-hosted' || 'ubuntu-latest' }}
    timeout-minutes: 180  # 3 hours maximum
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Ensure Poky sources
        run: |
          if [ ! -e yocto/poky/oe-init-build-env ]; then
            git clone --depth 1 https://git.yoctoproject.org/git/poky yocto/poky
          fi

      - name: Ensure meta-openembedded layer
        run: |
          if [ ! -e yocto/meta-openembedded/meta-oe ]; then
            git clone --depth 1 https://github.com/openembedded/meta-openembedded.git yocto/meta-openembedded
          fi

      - name: Set up Poky build environment
        run: |
          source yocto/poky/oe-init-build-env yocto/build
          # Work around occasional Meson clock skew errors
          # by cleaning the pixman recipe before building
          bitbake -c clean pixman || true
          # Also clean glib to avoid intermittent Meson failures
          bitbake -c clean glib-2.0-native || true
          # And clean the glib-initial recipe which sometimes hits
          # the same Meson clock skew issue
          bitbake -c clean glib-2.0-initial || true
          bitbake rust-spray-image

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-spray-image
          path: yocto/build/tmp/deploy/images
